version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.3
        nodejs: 10
  pre_build:
    commands:
      - echo Build started on `date`
  build:
   commands:
     - composer --version
     - echo Installing composer deps
     - composer install --ignore-platform-reqs
     - php artisan ecommerce:install --force
     - npm install
     - npm run production
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'